### ISSUE TITLE
Problem when using @enum writable

### ISSUE THREAD

**Issue by 0xibram** [lnxg33k/webhandler#20]
When I use `@enum writable` I always get the following:

```
Traceback (most recent call last):
  File "./webhandler.py", line 82, in <module>
    commander.BackConnect()                                 # Call BackConnect method to handle input
  File "/home/ibram/webhandler/core/libs/executer.py", line 77, in BackConnect
    self.commands[command_list[0]](command_list)
  File "/home/ibram/webhandler/core/libs/executer.py", line 248, in enum
    enumerate.writable()
  File "/home/ibram/webhandler/modules/enumerate.py", line 182, in writable
    cmd = "find {0} -depth -perm -0002 -type d".format(linux.get_doc_root())
  File "/home/ibram/webhandler/core/libs/shell_handler.py", line 23, in get_doc_root
    distrib_description = make_request.get_page_source(command)[0].lower()
IndexError: list index out of range
```

**Comment by lnxg33k** [comment]
Hi @P3R0 I will work on it and will be fixed by next week.

**Comment by lnxg33k** [comment]
issue should be resolved in the last commits.
